<?php
/**
 * Exports Actions
 *
 * These are actions related to exporting data from WalkTheCounty.
 *
 * @package     WalkTheCounty
 * @subpackage  Admin/Export
 * @copyright   Copyright (c) 2016, WalkTheCountyWP
 * @license     https://opensource.org/licenses/gpl-license GNU Public License
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Process the download file generated by a batch export.
 *
 * @since 1.5
 * @return void
 */
function walkthecounty_process_batch_export_form() {

	if ( ! wp_verify_nonce( $_REQUEST['nonce'], 'walkthecounty-batch-export' ) ) {
		wp_die( esc_html__( 'We\'re unable to recognize your session. Please refresh the screen to try again; otherwise contact your website administrator for assistance.', 'walkthecounty' ), esc_html__( 'Error', 'walkthecounty' ), array(
			'response' => 403,
		) );
	}

	require_once WALKTHECOUNTY_PLUGIN_DIR . 'includes/admin/tools/export/class-batch-export.php';

	/**
	 * Fires before batch export.
	 *
	 * @since 1.5
	 *
	 * @param string $class Export class.
	 */
	do_action( 'walkthecounty_batch_export_class_include', $_REQUEST['class'] );

	$export = new $_REQUEST['class'];
	$export->export();

}

add_action( 'walkthecounty_form_batch_export', 'walkthecounty_process_batch_export_form' );

/**
 * Exports earnings for a specified time period.
 *
 * WalkTheCounty_Earnings_Export class.
 *
 * @since 1.5
 * @return void
 */
function walkthecounty_export_earnings() {
	require_once WALKTHECOUNTY_PLUGIN_DIR . 'includes/admin/tools/export/class-export-earnings.php';

	$earnings_export = new WalkTheCounty_Earnings_Export();

	$earnings_export->export();
}

add_action( 'walkthecounty_earnings_export', 'walkthecounty_export_earnings' );

/**
 * Exports WalkTheCounty's core settings.
 *
 * WalkTheCounty_Core_Settings class.
 *
 * @since 1.8.17
 * @return void
 */
function walkthecounty_core_settings_export() {
	require_once WALKTHECOUNTY_PLUGIN_DIR . 'includes/admin/tools/export/class-core-settings-export.php';

	$core_settings = new WalkTheCounty_Core_Settings_Export();

	$core_settings->export();
}

add_action( 'walkthecounty_core_settings_export', 'walkthecounty_core_settings_export' );


/**
 * Add a hook allowing extensions to register a hook on the batch export process.
 *
 * @since  1.5
 * @return void
 */
function walkthecounty_register_batch_exporters() {
	if ( is_admin() ) {
		/**
		 * Fires in the admin, while plugins loaded.
		 *
		 * Allowing extensions to register a hook on the batch export process.
		 *
		 * @since 1.5
		 *
		 * @param string $class Export class.
		 */
		do_action( 'walkthecounty_register_batch_exporter' );
	}
}

add_action( 'plugins_loaded', 'walkthecounty_register_batch_exporters' );

/**
 * Register the donors batch exporter.
 *
 * @since  1.5.2
 */
function walkthecounty_register_donors_batch_export() {
	add_action( 'walkthecounty_batch_export_class_include', 'walkthecounty_include_donors_batch_processor', 10, 1 );
}

add_action( 'walkthecounty_register_batch_exporter', 'walkthecounty_register_donors_batch_export', 10 );

/**
 * Loads the donors batch process if needed.
 *
 * @since  1.5.2
 *
 * @param  string $class The class being requested to run for the batch export.
 *
 * @return void
 */
function walkthecounty_include_donors_batch_processor( $class ) {

	if ( 'WalkTheCounty_Batch_Donors_Export' === $class ) {
		require_once WALKTHECOUNTY_PLUGIN_DIR . 'includes/admin/tools/export/class-batch-export-donors.php';
	}

}
